CREATE TABLE boletim
(
    id BIGINT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    media DECIMAL(2,1) NOT NULL,
    aluno BIGINT NOT NULL FOREIGN KEY REFERENCES aluno (id),
    periodo BIGINT NOT NULL FOREIGN KEY REFERENCES periodo (id),
);